# Generated by Django 5.2.2 on 2025-12-08 02:29

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration is intentionally a no-op. The field should remain on the model,
    and dropping it caused issues when the column was already missing in some DBs.
    """

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = []
