# Generated by Django 5.2.2 on 2025-12-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='name_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
