# Generated by Django 5.2.3 on 2025-07-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='customusers',
            name='is_senior_or_pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='valid_id_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('driver_license', "Driver's License"), ('national_id', 'National ID'), ('sss_id', 'SSS ID'), ('umid', 'Unified Multi-Purpose ID (UMID)'), ('philhealth_id', 'PhilHealth ID'), ('prc_id', 'PRC ID'), ('student_id', 'Student ID'), ('senior_citizen_id', 'Senior Citizen ID'), ('other', 'Other Government-Issued ID')], max_length=60, null=True),
        ),
    ]
