# Generated by Django 5.2.3 on 2025-07-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0002_customer_customusers_is_senior_or_pwd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
