# Generated by Django 5.2.2 on 2025-12-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0002_remove_customusers_name_last_updated'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE users ADD COLUMN IF NOT EXISTS name_last_updated date;",
            reverse_sql="ALTER TABLE users DROP COLUMN IF EXISTS name_last_updated;",
        ),
    ]
