# Generated by Django 5.2.3 on 2025-07-17 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_commissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commissions',
        ),
    ]
