# Generated by Django 5.2.3 on 2025-07-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
