# Generated by Django 5.2.2 on 2025-12-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='payment_method',
            field=models.CharField(choices=[('physical', 'Physical Payment'), ('gcash', 'GCash'), ('on_site', 'On-Site')], default='gcash', max_length=20),
        ),
    ]
