# Generated by Django 5.2.3 on 2025-07-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookings_is_discounted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraveOnCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CraveOnItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.BinaryField()),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CraveOnUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('user_img', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='has_food_order',
            field=models.BooleanField(default=False),
        ),
    ]
