# Generated by Django 5.2.2 on 2025-10-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_delete_craveoncategory_delete_craveonitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='paymongo_payment_id',
            field=models.CharField(blank=True, help_text='PayMongo payment ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='paymongo_source_id',
            field=models.CharField(blank=True, help_text='PayMongo source ID', max_length=255, null=True),
        ),
    ]
